### ISSUE TITLE
Introduce `@latest` support for Setup Ballerina

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/setup-ballerina#3]
**Description:**
This is a requirement request to introduce `@latest` support for `Setup Ballerina` so that to use the latest available Ballerina version

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This is fixed in https://github.com/ballerina-platform/setup-ballerina/pull/4

**Comment by keizer619** [comment]
This is released in 1.1.0
