### ISSUE TITLE
Action defaults to old version of Ballerina

### ISSUE THREAD

**Issue by rukmal** [ballerina-platform/setup-ballerina#5]
**Description:**
This action currently defaults to Ballerina version `2201.3.2`. Ideal fix would be for it to default to a later/latest version IMO.
**Suggested Labels:**
enhancement
**Steps to reproduce:**
Use the connector in a GitHub Workflow

**Comment by keizer619** [comment]
Yes its better to update automatically it  as we release
For now i bumped now manually https://github.com/ballerina-platform/setup-ballerina/pull/9
